### PR TITLE
Change from Conda to pip-tools

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
This PR replaces the existing Conda-based approach to managing the dependencies to a more generalisable pip-tools approach. This change is reflected in the `Build and Deploy` Action and the README.

It also adds a GitHub Action for running the Unit tests.

@alastairhmoore The tests are currently failing, this is something you should look into.

### CODE REVIEW

**Review by alexdewar — APPROVED** [review]
LGTM! Nice work, knocking this up so fast @AdrianDAlessandro.

We should make doubly sure that the CI is still producing usable binaries before we merge it though, I think.

**Comment by AdrianDAlessandro** [comment]
Yes, we should confirm the binary works. @alastairhmoore can you confirm the release here works? https://github.com/AdrianDAlessandro/sap-elospheres-audiovisual-test/releases/tag/test-pip-tools

**Comment by alastairhmoore** [comment]
Many thanks for this.

I’m not going to have access to my Windows system until I’m back in the office next week, I’m afraid. I’ll test it then.

On 30 Jun 2023, at 17:52, AdrianDAlessandro ***@***.***> wrote:



Yes, we should confirm the binary works. @alastairhmoore<https://github.com/alastairhmoore> can you confirm the release here works? https://github.com/AdrianDAlessandro/sap-elospheres-audiovisual-test/releases/tag/test-pip-tools

**Comment by AdrianDAlessandro** [comment]
> Many thanks for this. I’m not going to have access to my Windows system until I’m back in the office next week, I’m afraid. I’ll test it then.

No problem @alastairhmoore 

I have merged this PR into the `dev` branch for this fork since Alex was able to run the executable. Still check this before merging [that PR](https://github.com/ImperialCollegeLondon/sap-elospheres-audiovisual-test/pull/1) though.

**Pull request merged**
